# Generated by Django 4.2.5 on 2023-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerid', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=10)),
                ('password', models.CharField(default='klu123', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
    ]
