# Generated by Django 4.2.5 on 2023-10-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
