# Generated by Django 4.2.5 on 2023-10-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
